### ISSUE TITLE
Half ratings not getting a different class

### ISSUE THREAD

**Issue by simonkuran** [doublesecretagency/craft-starratings#12] opened 2020-07-22 09:07 UTC
Both when using `do craft.starRatings.setIcons` (with "full" or "4/4" syntax) and using the defaults the class doesn't change for half ratings. The Star Increment Size CP setting doesn't have any affect.
<img width="742" alt="Screen Shot 2020-07-22 at 1 04 23 PM" src="https://user-images.githubusercontent.com/41410727/88157502-e5cfb700-cc1b-11ea-8222-2f5ec01b5389.png">

```
{% do craft.starRatings.setIcons({
    'full'  : '<i class="fa 1 fa-star"></i>',
    'half'  : '<i class="fa 2 fa-star-half"></i>',
    'empty' : '<i class="fa 3 fa-star"></i>',
}) %}

<div class="recipe-stat-bar__item recipe-stat-bar__stars">
    {{ craft.starRatings.lockedStars(craft.starRatings.avgRating(entry.id)) }}
    {{ craft.starRatings.avgRating(entry.id) }}
</div>
```

**Comment by lindseydiloreto** [comment] 2020-08-04 18:03
I just tested this locally, and everything seems to be working normally for me. Using the "Star Increment Size" dropdown in the plugin settings, I'm able to switch between all three display variations, and each of them is showing the correct number of full, half, and quarter icons respectively.

<img width="784" alt="stars@2x" src="https://user-images.githubusercontent.com/5309692/89327964-8de47780-d641-11ea-9cf7-2370bb7f2bcf.png">

When I select "Quarter Stars", my page is indeed showing quarter stars. Ditto for "Half" and "Full".

I'm going to close this as I can't seem to reproduce it. If you're still having this problem, please DM me on Craft Discord.

**Closed as completed by lindseydiloreto** 2020-08-04 18:03 UTC

**Comment by simonkuran** [comment] 2020-08-05 07:16
Somehow it's working now even though that code hasn't changed. No idea what caused this. Sorry for the trouble!

**Comment by lindseydiloreto** [comment] 2020-08-05 17:08
Ok great, glad it worked itself out. Thanks for reporting back! 👍
