### ISSUE TITLE
v2.2.1 causes entry pages to take 1min+ to load

### ISSUE THREAD

**Issue by dmatthams** [doublesecretagency/craft-starratings#18] opened 2021-11-24 15:11 UTC
Recently updated several plugins, and client complained of entries taking a long time to load in the control panel. Whittled the issue down to Star Ratings v2.2.1. Have temporarily rolled back to v2.2.0 which works fine.

Happening on entries where there is no star rating field.

This only happens on production server, not local development environment. 

PHP version | 7.4.26
Linux 3.10.0-957.27.2.el7.x86_64
MySQL 5.5.68
Craft edition & version | Craft Pro 3.7.21

**Comment by lindseydiloreto** [comment] 2021-11-24 18:55
Thanks for reporting @dmatthams, I think I know what the problem is.

Sounds like a change I made recently on behalf of GraphQL was a bit heavy handed. You can stick with v2.2.0 until I get it sorted out.

Out of curiosity, about how many entries do you have across the entire system?

**Comment by dmatthams** [comment] 2021-11-24 21:38
Probably around 100 entries, although there's 10 locales with lots of revisions and drafts.

Thanks, will keep an eye out for an update :)

**Comment by lindseydiloreto** [comment] 2022-01-11 06:27
This is fixed in **v2.2.2**. 👍 

Sorry for the delay, thanks for reporting this issue!

**Closed as completed by lindseydiloreto** 2022-01-11 06:27 UTC
Labels: bug

**Comment by dmatthams** [comment] 2022-01-11 10:34
Great, thanks!
